.TH ez-ntpd 1 "August 25, 2015"
.SH NAME
ez-ntpd
.SH SYNOPSIS
.B ez-ntpd [options]
.SH DESCRIPTION
.B ez-ntpd
is the server portion of the ez-ntp application.
.SH OPTIONS
.TP
.BI --disable-all-logs
Disable logging.
.TP
.BI --host " IP-ADDRESS"
The IP address of the remote server.
.TP
.BI --port " PORT"
The IP port of the remote server.
.SH AUTHOR(S)
.B Alexis Megas
