.TH ez-ntpc 1 "October 23, 2016"
.SH NAME
ez-ntpc
.SH SYNOPSIS
.B ez-ntpc [options]
.SH DESCRIPTION
.B ez-ntpc
is the client portion of the ez-ntp application.
.SH OPTIONS
.TP
.BI --disable-all-logs
Disable logging.
.TP
.BI --host " IP-ADDRESS"
The IP address of the remote server.
.TP
.BI --port " PORT"
The IP port of the remote server.
.TP
.BI --shutdown-before-close
Issue shutdown() before close(). Disabled by default.
.TP
.BI --so-linger " timeout"
Set the SO_LINGER socket option to the specified value before issuing close().
.SH NOTES
Computers should be in the same time zone. Please use only trusted time sources.
.SH AUTHOR(S)
.B Alexis Megas
